// Generated by Wrangler on Thu Aug 15 2024 16:18:37 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE: D1Database;
	AI: Ai;
}
