name = "is-it-chill-tonight"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "is-it-chill-tonight-db"
database_id = "fc3f808b-3a8d-4bff-88f5-3e82eaa4d9a2"
